export const bodies = [
  { id:'sun', name:'Sun', label:'☀ Sun', type:'Звезда', distance:'Центр системы', diameter:'1 392 700 км', year:'—', temp:'5 500 °C', radius:2.2, orbit:0, color:'#ffb23e', emissive:'#ff6b22', speed:0, description:'Наша звезда — гигантский шар плазмы, содержащий 99,86% массы Солнечной системы.', facts:['Свет от Солнца идёт до Земли около 8 минут 20 секунд.'] },
  { id:'mercury', name:'Mercury', label:'☿ Mercury', type:'Каменистая планета', distance:'57,9 млн км', diameter:'4 879 км', year:'88 суток', temp:'167 °C', radius:.16, orbit:4.5, color:'#a7a9ad', speed:1.7, description:'Самая маленькая и быстрая планета системы.', facts:['На дневной стороне температура достигает 427 °C.'] },
  { id:'venus', name:'Venus', label:'♀ Venus', type:'Каменистая планета', distance:'108,2 млн км', diameter:'12 104 км', year:'224,7 суток', temp:'464 °C', radius:.28, orbit:6.2, color:'#d9a35f', speed:1.25, description:'Мир плотных облаков серной кислоты и мощнейшего парникового эффекта.', facts:['Сутки на Венере длиннее её года.'] },
  { id:'earth', name:'Earth', label:'🌍 Earth', type:'Каменистая планета', distance:'149,6 млн км', diameter:'12 742 км', year:'365,25 суток', temp:'15 °C', radius:.32, orbit:8.3, color:'#2879d1', speed:1, description:'Наш живой дом с океанами, материками и единственной известной биосферой.', facts:['Землю защищают магнитное поле и атмосфера.'], moon:true },
  { id:'mars', name:'Mars', label:'♂ Mars', type:'Каменистая планета', distance:'227,9 млн км', diameter:'6 779 км', year:'687 суток', temp:'−63 °C', radius:.22, orbit:10.3, color:'#b85642', speed:.8, description:'Красная планета с древними долинами, вулканами и полярным льдом.', facts:['На Марсе находится крупнейший вулкан Солнечной системы — Олимп.'] },
  { id:'jupiter', name:'Jupiter', label:'♃ Jupiter', type:'Газовый гигант', distance:'778,5 млн км', diameter:'139 820 км', year:'11,86 лет', temp:'−110 °C', radius:1.05, orbit:14, color:'#c28e69', speed:.43, description:'Крупнейшая планета, быстро вращающийся гигант с Большим красным пятном.', facts:['В объёме Юпитера поместилось бы около 1 321 Земли.'] },
  { id:'saturn', name:'Saturn', label:'♄ Saturn', type:'Газовый гигант', distance:'1,43 млрд км', diameter:'116 460 км', year:'29,45 лет', temp:'−140 °C', radius:.9, orbit:18, color:'#d6b276', speed:.32, description:'Элегантный гигант с системой ледяных колец.', facts:['Кольца состоят из миллиардов частиц льда и камня.'], rings:true },
  { id:'uranus', name:'Uranus', label:'♅ Uranus', type:'Ледяной гигант', distance:'2,87 млрд км', diameter:'50 724 км', year:'84 года', temp:'−195 °C', radius:.58, orbit:22, color:'#77cfd0', speed:.22, description:'Холодный голубовато-зелёный мир, вращающийся почти на боку.', facts:['Наклон оси Урана составляет около 98°.'] },
  { id:'neptune', name:'Neptune', label:'♆ Neptune', type:'Ледяной гигант', distance:'4,5 млрд км', diameter:'49 244 км', year:'164,8 лет', temp:'−200 °C', radius:.56, orbit:26, color:'#3e62c7', speed:.17, description:'Самый дальний гигант с самыми быстрыми ветрами.', facts:['Скорость ветров на Нептуне достигает 2 100 км/ч.'] },
  { id:'pluto', name:'Pluto', label:'♇ Pluto', type:'Карликовая планета', distance:'5,9 млрд км', diameter:'2 377 км', year:'248 лет', temp:'−229 °C', radius:.12, orbit:30, color:'#a99b91', speed:.1, description:'Ледяной карликовый мир пояса Койпера.', facts:['Плутон не очистил окрестность своей орбиты.'] }
]
export const stars = ['Sirius','Vega','Betelgeuse','Polaris']
